* = * "Intro Text"
INTROTEXT: {
	.encoding "screencode_upper"
	.text "LOREM IPSUM "
	.text "ADIPISCING ELIT, SED DO EIUSMOD TEMPOR "
	.text "INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. "
	.text "UT ENIM AD MINIM VENIAM, QUIS NOSTRUD "
	.text "EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP "
	.text "EX EA COMMODO CONSEQUAT. DUIS AUTE IRURE DOLOR "
	.text "IN REPREHENDERIT IN VOLUPTATE VELIT ESSE CILLUM "
	.text "DOLORE EU FUGIAT NULLA PARIATUR. EXCEPTEUR SINT "
	.text "OCCAECAT CUPIDATAT NON PROIDENT, SUNT IN CULPA "
	.text "QUI OFFICIA DESERUNT MOLLIT ANIM ID EST LABORUM."
	.byte $ff
}


